server:
  port: 9090
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/stdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qge;tle13
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  logging:
    level:
      org.springframework: INFO
      org.springframework.web: DEBUG